name: publish_policy

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  publish-policy:
    runs-on: ubuntu-latest
    name: build

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read policy config
      id: policy-config
      uses: gertd/yaml-reader-action@v1.0
      with:
        file: .github/config-policy.yaml

    - name: Calc Tags
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ steps.policy-config.outputs.server }}/${{ steps.policy-config.outputs.repo }}
        flavor: |
          latest=auto
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Policy Login
      id: policy-login
      uses: opcr-io/policy-login-action@v2
      with:
        username: ${{ steps.policy-config.outputs.username }}
        password: ${{ secrets.ASERTO_POLICY_PUBLISH_KEY }}
        server: ${{ steps.policy-config.outputs.server }}

    - name: Policy Build
      id: policy-build
      uses: opcr-io/policy-build-action@v2
      with:
        src: content/src
        tag: ${{ steps.policy-config.outputs.repo }}
        revision: "$GITHUB_SHA"
      env:
        POLICY_DEFAULT_DOMAIN: ${{ steps.config.outputs.server }}

    - name: Policy Tag
      id: policy-tag
      uses: opcr-io/policy-tag-action@v2
      with:
        source_tag: ${{ steps.policy-config.outputs.repo }}
        target_tags: ${{ steps.meta.outputs.tags }}
      env:
        POLICY_DEFAULT_DOMAIN: ${{ steps.policy-config.outputs.server }}

    - name: Policy Push
      id: policy-push
      uses: opcr-io/policy-push-action@v2
      with:
        tags: ${{ steps.meta.outputs.tags }}
      env:
        POLICY_DEFAULT_DOMAIN: ${{ steps.policy-config.outputs.server }}

    - name: Policy Logout
      id: policy-logout
      uses: opcr-io/policy-logout-action@v2
      with:
        server: ${{ steps.policy-config.outputs.server }}
